name = "tasker-web"
compatibility_date = "current date"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "insert your DB name"
database_id = "put your own DB ID here."
