name = "tasker-web"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tasker-db"
database_id = "94aa8790-c193-4fbc-a6e6-f5ed8d9498db"
